/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited. It is regenerated by `next dev` and
// `next build`. Tracked here so the bare-clone typecheck job has the types.
